### ISSUE TITLE
作者写的图片控件很赞，希望这个也要继续更新呢，谢谢，加油加油

### ISSUE THREAD

**Issue by hupo376787** [h82258652/HN.Social.Weibo#2]

**Comment by h82258652** [comment]
不好意思，你发这个 issue 的时候我刚刚开始重构没多久。这几个月其实一直在改，主要是要调整微博返回错误时的处理。现在这段时间闲了点，总算重构完了，也发了个 nuget 包算是完成了一个目标吧。
